# Generated by Django 5.2.8 on 2025-11-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('calificacion', models.FloatField(default=0.0)),
                ('total_valoraciones', models.PositiveIntegerField(default=0)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('precio_final', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('envio_gratis', models.BooleanField(default=False)),
                ('costo_envio', models.DecimalField(decimal_places=2, default=2.9, max_digits=6)),
                ('cantidad_disponible', models.PositiveIntegerField(default=0)),
                ('descripcion', models.TextField(blank=True)),
                ('especificaciones', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='libros/')),
            ],
        ),
    ]
