# Generated by Django 5.2.8 on 2025-11-16 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_tipolibro_libro_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='total_valoraciones',
        ),
    ]
