# Generated by Django 5.2.8 on 2025-11-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0004_remove_libro_total_valoraciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='editorial',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='libro',
            name='idioma',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='libro',
            name='paginas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='libro',
            name='year_publicacion',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
