# Generated by Django 5.2.8 on 2025-11-16 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0005_libro_editorial_libro_idioma_libro_paginas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='especificaciones',
        ),
    ]
