# Generated by Django 5.2.8 on 2025-11-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0006_remove_libro_especificaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='portadas/'),
        ),
    ]
